# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
permalink: /:year/:month/:title/
title: Andri Kurnia - Web Developer and Web Designer
email: andrikurnia@live.com
description: >
  I am Andri Kurnia and I am absolute. I awarded myself super awesome web developer and designer. Yeah!
baseurl: ""
url: "https://andrkrn.github.io"
twitter_username: jekyllrb
github_username:  andrkrn

# Build settings
markdown: kramdown
